### ISSUE TITLE
[Blocker] Deprecated slack API makes this resource unusable

### ISSUE THREAD

**Issue by varmakarthik12** [jleben/slack-chat-resource#7]
The latest slack API deprecations break this resource & make it unusable. Is there any plan to fix this?

**Comment by varmakarthik12** [comment]
@jleben , @Leo3738

**Comment by jleben** [comment]
@varmakarthik12 Unfortunately, I have abandoned development and maintanance of this resource. I would be happy for someone else to adopt the project.

**Comment by varmakarthik12** [comment]
That's sad to hear. I found this resource very useful. I'm happy to work on a clone of this project & maintain it.

**Comment by varmakarthik12** [comment]
For someone who found this resource useful. There is a workable clone https://github.com/varmakarthik12/slack-chat-resource that fixes the blockers that are created cause of slack deprication
